### ISSUE TITLE
Update insights overview card language

### ISSUE THREAD

**Issue by michaelwheeler** [academic-innovation/frontend-app-mogc-partners#58]
![Image](https://github.com/academic-innovation/frontend-app-mogc-partners/assets/763388/80b153b2-5172-4de5-9871-fce5360ceb42)

**Comment by Wattsun64** [comment]
For the *Total Course Enrollments* and *Total Course Completions*, adding *Course* causes the *Total Course Completions* text to drop to another line. Which makes things looks "off balance" (see image). Is this something we're okay with?


![Image](https://github.com/academic-innovation/frontend-app-mogc-partners/assets/20584164/5e81462c-6790-4f6a-99ce-153de93802de)

**Comment by michaelwheeler** [comment]
> Is this something we're okay with?

@Wattsun64 I don't think we're okay with that, but ultimately it's up to @sophiazumich

**Comment by Wattsun64** [comment]
@sophiazumich @michaelwheeler for what it's worth, removing the word *Courses* gets us back to status quo



![Image](https://github.com/academic-innovation/frontend-app-mogc-partners/assets/20584164/2b64eff4-13b6-4278-932f-a87725221686)

**Comment by sophiazumich** [comment]
@Wattsun64 Would you be able to add a break tag <br> or <br/> between: 
- "Total" and "Courses"
- "Total" and "Learners" (Members should be changed to Learners) 
- "Total Course" and "Enrollments"
- "Total Course" and "Completions" 

?

**Comment by Wattsun64** [comment]
Would something like this work?

![Image](https://github.com/academic-innovation/frontend-app-mogc-partners/assets/20584164/ac22a11f-f73a-4002-bb8f-6bb535a02a84)

**Comment by sophiazumich** [comment]
@Wattsun64 it would be a good plan b! Are we unable to add the break after "Course" for the 2 panels on the right? Adding the break there would help the visual balance of the label, since the character count/length of "Enrollments" and "Completions" is fairly close to that of "Total Course"

<img width="991" alt="Screenshot 2023-11-21 at 10 24 35 AM" src="https://github.com/academic-innovation/frontend-app-mogc-partners/assets/40248497/fa9255de-cebd-4d33-b6a4-aa3f114e5dbe">

**Comment by Wattsun64** [comment]
@sophiazumich ask and you shall recieve.


![Image](https://github.com/academic-innovation/frontend-app-mogc-partners/assets/20584164/bbccd0db-6190-4dcc-8ecb-1371223abb82)
